# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Group.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserProfile_pb2 as UserProfile__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bGroup.proto\x12\rrpcManagement\x1a\x11UserProfile.proto\"x\n\x05Group\x12\x0f\n\x07groupId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0e\n\x06scopes\x18\x04 \x03(\t\x12+\n\x07members\x18\x05 \x03(\x0b\x32\x1a.rpcManagement.UserProfileb\x06proto3')



_GROUP = DESCRIPTOR.message_types_by_name['Group']
Group = _reflection.GeneratedProtocolMessageType('Group', (_message.Message,), {
  'DESCRIPTOR' : _GROUP,
  '__module__' : 'Group_pb2'
  # @@protoc_insertion_point(class_scope:rpcManagement.Group)
  })
_sym_db.RegisterMessage(Group)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GROUP._serialized_start=49
  _GROUP._serialized_end=169
# @@protoc_insertion_point(module_scope)
