# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserManagementService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserProfile_pb2 as UserProfile__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import Group_pb2 as Group__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bUserManagementService.proto\x12\rrpcManagement\x1a\x11UserProfile.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bGroup.proto2\xaf\x04\n\x15UserManagementService\x12K\n\x11\x43reateUserProfile\x12\x1a.rpcManagement.UserProfile\x1a\x1a.rpcManagement.UserProfile\x12H\n\x0eGetUserProfile\x12\x1a.rpcManagement.UserProfile\x1a\x1a.rpcManagement.UserProfile\x12K\n\x11UpdateUserProfile\x12\x1a.rpcManagement.UserProfile\x1a\x1a.rpcManagement.UserProfile\x12G\n\x11\x44\x65leteUserProfile\x12\x1a.rpcManagement.UserProfile\x1a\x16.google.protobuf.Empty\x12\x39\n\x0b\x43reateGroup\x12\x14.rpcManagement.Group\x1a\x14.rpcManagement.Group\x12\x36\n\x08GetGroup\x12\x14.rpcManagement.Group\x1a\x14.rpcManagement.Group\x12\x39\n\x0bUpdateGroup\x12\x14.rpcManagement.Group\x1a\x14.rpcManagement.Group\x12;\n\x0b\x44\x65leteGroup\x12\x14.rpcManagement.Group\x1a\x16.google.protobuf.Emptyb\x06proto3')



_USERMANAGEMENTSERVICE = DESCRIPTOR.services_by_name['UserManagementService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERMANAGEMENTSERVICE._serialized_start=108
  _USERMANAGEMENTSERVICE._serialized_end=667
# @@protoc_insertion_point(module_scope)
